#!/bin/bash
# Study Session Tracker - Quick Commands for Mac Terminal

echo "📚 Study Session Tracker - Command Guide"
echo "========================================"
echo ""
echo "Navigation:"
echo "  cd /Users/ruan/Docs/RevisionApp"
echo ""
echo "Development:"
echo "  npm run dev        # Start dev server (http://localhost:3000)"
echo "  npm run build      # Build for production"
echo "  npm start          # Run production build"
echo "  npm run lint       # Check code quality"
echo ""
echo "Browser:"
echo "  # Open in your browser:"
echo "  http://localhost:3000"
echo ""
echo "Terminal Control:"
echo "  Ctrl+C             # Stop dev server"
echo "  npm run dev        # Restart dev server"
echo ""
echo "Useful Shortcuts:"
echo "  Cmd+Shift+R        # Hard refresh (browser cache clear)"
echo "  Cmd+Option+I       # Open DevTools"
echo "  Cmd+Shift+C        # Inspect element"
echo ""
echo "View Source Code:"
echo "  Main app:          src/app/page.tsx"
echo "  Timer:             src/components/Timer.tsx"
echo "  Storage hook:      src/hooks/useLocalStorage.ts"
echo "  PWA config:        public/manifest.json"
echo ""
echo "Clear Data (localStorage):"
echo "  # In DevTools → Application → Storage → Clear site data"
echo "  # Or in browser console:"
echo "  localStorage.clear()"
echo ""
echo "Service Worker:"
echo "  # In DevTools → Application → Service Workers"
echo "  # Unregister to force update"
echo ""
echo "Next Steps:"
echo "  1. npm run dev"
echo "  2. Open http://localhost:3000"
echo "  3. Click 'Start Session' button"
echo "  4. Refresh page to see persistence!"
